# This is a basic workflow to help you get started with Actions

name: Flutter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.20.4'
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          STORAGE_PASSWORD: ${{ secrets.STORAGE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          HOME: /home/runner/work/flutter_dmzj/flutter_dmzj/android/test.properties
      - run: echo "${{ secrets.KEY_JKS }}" > /home/test.jks && echo "storePassword=${{ secrets.STORAGE_PASSWORD }}\\nkeyPassword=${{ secrets.KEY_PASSWORD }}\\nkeyAlias=${{ secrets.KEY_ALIAS }}\\nstoreFile=/home/test.jks" > $HOME
      - run: flutter pub get
      - run: flutter build apk
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.4'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
